application: persistent-cache-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Enable the interactive GAE console when deployed (vs just running locally)
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /test/.*
  script: test.application
  secure: always

